// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: datastore/pb/log.proto

package pb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type LogPb struct {
	Index                uint64   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Term                 uint64   `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Type                 uint64   `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Extensions           []byte   `protobuf:"bytes,5,opt,name=extensions,proto3" json:"extensions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogPb) Reset()         { *m = LogPb{} }
func (m *LogPb) String() string { return proto.CompactTextString(m) }
func (*LogPb) ProtoMessage()    {}
func (*LogPb) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d0737b53596c97, []int{0}
}
func (m *LogPb) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogPb.Unmarshal(m, b)
}
func (m *LogPb) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogPb.Marshal(b, m, deterministic)
}
func (m *LogPb) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogPb.Merge(m, src)
}
func (m *LogPb) XXX_Size() int {
	return xxx_messageInfo_LogPb.Size(m)
}
func (m *LogPb) XXX_DiscardUnknown() {
	xxx_messageInfo_LogPb.DiscardUnknown(m)
}

var xxx_messageInfo_LogPb proto.InternalMessageInfo

func (m *LogPb) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *LogPb) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *LogPb) GetType() uint64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *LogPb) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *LogPb) GetExtensions() []byte {
	if m != nil {
		return m.Extensions
	}
	return nil
}

func init() {
	proto.RegisterType((*LogPb)(nil), "pb.LogPb")
}

func init() { proto.RegisterFile("datastore/pb/log.proto", fileDescriptor_51d0737b53596c97) }

var fileDescriptor_51d0737b53596c97 = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4b, 0x49, 0x2c, 0x49,
	0x2c, 0x2e, 0xc9, 0x2f, 0x4a, 0xd5, 0x2f, 0x48, 0xd2, 0xcf, 0xc9, 0x4f, 0xd7, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xaa, 0xe4, 0x62, 0xf5, 0xc9, 0x4f, 0x0f, 0x48, 0x12,
	0x12, 0xe1, 0x62, 0xcd, 0xcc, 0x4b, 0x49, 0xad, 0x90, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x09, 0x82,
	0x70, 0x84, 0x84, 0xb8, 0x58, 0x4a, 0x52, 0x8b, 0x72, 0x25, 0x98, 0xc0, 0x82, 0x60, 0x36, 0x58,
	0xac, 0xb2, 0x20, 0x55, 0x82, 0x19, 0x2a, 0x56, 0x59, 0x90, 0x0a, 0x12, 0x03, 0x59, 0x22, 0xc1,
	0xa2, 0xc0, 0xa8, 0xc1, 0x13, 0x04, 0x66, 0x0b, 0xc9, 0x71, 0x71, 0xa5, 0x56, 0x94, 0xa4, 0xe6,
	0x15, 0x67, 0xe6, 0xe7, 0x15, 0x4b, 0xb0, 0x82, 0x65, 0x90, 0x44, 0x9c, 0x98, 0xa2, 0x18, 0x92,
	0xd8, 0xc0, 0x2e, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x20, 0x51, 0x12, 0x4a, 0xa3, 0x00,
	0x00, 0x00,
}
