// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: consensus/rpc/fs.proto

package consensus

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Operation_Code int32

const (
	Operation_CP    Operation_Code = 0
	Operation_MV    Operation_Code = 1
	Operation_RM    Operation_Code = 2
	Operation_MKDIR Operation_Code = 3
	Operation_Ls    Operation_Code = 4
)

var Operation_Code_name = map[int32]string{
	0: "CP",
	1: "MV",
	2: "RM",
	3: "MKDIR",
	4: "Ls",
}

var Operation_Code_value = map[string]int32{
	"CP":    0,
	"MV":    1,
	"RM":    2,
	"MKDIR": 3,
	"Ls":    4,
}

func (x Operation_Code) String() string {
	return proto.EnumName(Operation_Code_name, int32(x))
}

func (Operation_Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_14fcbe24d8939e1f, []int{5, 0}
}

type Ctx struct {
	Pre                  string   `protobuf:"bytes,1,opt,name=pre,proto3" json:"pre,omitempty"`
	Next                 string   `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ctx) Reset()         { *m = Ctx{} }
func (m *Ctx) String() string { return proto.CompactTextString(m) }
func (*Ctx) ProtoMessage()    {}
func (*Ctx) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fcbe24d8939e1f, []int{0}
}
func (m *Ctx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ctx.Unmarshal(m, b)
}
func (m *Ctx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ctx.Marshal(b, m, deterministic)
}
func (m *Ctx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ctx.Merge(m, src)
}
func (m *Ctx) XXX_Size() int {
	return xxx_messageInfo_Ctx.Size(m)
}
func (m *Ctx) XXX_DiscardUnknown() {
	xxx_messageInfo_Ctx.DiscardUnknown(m)
}

var xxx_messageInfo_Ctx proto.InternalMessageInfo

func (m *Ctx) GetPre() string {
	if m != nil {
		return m.Pre
	}
	return ""
}

func (m *Ctx) GetNext() string {
	if m != nil {
		return m.Next
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fcbe24d8939e1f, []int{1}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type DirPath struct {
	Dir                  string   `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Ctx                  *Ctx     `protobuf:"bytes,3,opt,name=ctx,proto3" json:"ctx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DirPath) Reset()         { *m = DirPath{} }
func (m *DirPath) String() string { return proto.CompactTextString(m) }
func (*DirPath) ProtoMessage()    {}
func (*DirPath) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fcbe24d8939e1f, []int{2}
}
func (m *DirPath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirPath.Unmarshal(m, b)
}
func (m *DirPath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirPath.Marshal(b, m, deterministic)
}
func (m *DirPath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirPath.Merge(m, src)
}
func (m *DirPath) XXX_Size() int {
	return xxx_messageInfo_DirPath.Size(m)
}
func (m *DirPath) XXX_DiscardUnknown() {
	xxx_messageInfo_DirPath.DiscardUnknown(m)
}

var xxx_messageInfo_DirPath proto.InternalMessageInfo

func (m *DirPath) GetDir() string {
	if m != nil {
		return m.Dir
	}
	return ""
}

func (m *DirPath) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *DirPath) GetCtx() *Ctx {
	if m != nil {
		return m.Ctx
	}
	return nil
}

type Path struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Ctx                  *Ctx     `protobuf:"bytes,2,opt,name=ctx,proto3" json:"ctx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Path) Reset()         { *m = Path{} }
func (m *Path) String() string { return proto.CompactTextString(m) }
func (*Path) ProtoMessage()    {}
func (*Path) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fcbe24d8939e1f, []int{3}
}
func (m *Path) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Path.Unmarshal(m, b)
}
func (m *Path) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Path.Marshal(b, m, deterministic)
}
func (m *Path) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Path.Merge(m, src)
}
func (m *Path) XXX_Size() int {
	return xxx_messageInfo_Path.Size(m)
}
func (m *Path) XXX_DiscardUnknown() {
	xxx_messageInfo_Path.DiscardUnknown(m)
}

var xxx_messageInfo_Path proto.InternalMessageInfo

func (m *Path) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Path) GetCtx() *Ctx {
	if m != nil {
		return m.Ctx
	}
	return nil
}

type Nodes struct {
	Node                 []*Nodes_Node `protobuf:"bytes,1,rep,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Nodes) Reset()         { *m = Nodes{} }
func (m *Nodes) String() string { return proto.CompactTextString(m) }
func (*Nodes) ProtoMessage()    {}
func (*Nodes) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fcbe24d8939e1f, []int{4}
}
func (m *Nodes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nodes.Unmarshal(m, b)
}
func (m *Nodes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nodes.Marshal(b, m, deterministic)
}
func (m *Nodes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nodes.Merge(m, src)
}
func (m *Nodes) XXX_Size() int {
	return xxx_messageInfo_Nodes.Size(m)
}
func (m *Nodes) XXX_DiscardUnknown() {
	xxx_messageInfo_Nodes.DiscardUnknown(m)
}

var xxx_messageInfo_Nodes proto.InternalMessageInfo

func (m *Nodes) GetNode() []*Nodes_Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type Nodes_Node struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 int64    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Size_                int64    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Hash                 string   `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nodes_Node) Reset()         { *m = Nodes_Node{} }
func (m *Nodes_Node) String() string { return proto.CompactTextString(m) }
func (*Nodes_Node) ProtoMessage()    {}
func (*Nodes_Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fcbe24d8939e1f, []int{4, 0}
}
func (m *Nodes_Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nodes_Node.Unmarshal(m, b)
}
func (m *Nodes_Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nodes_Node.Marshal(b, m, deterministic)
}
func (m *Nodes_Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nodes_Node.Merge(m, src)
}
func (m *Nodes_Node) XXX_Size() int {
	return xxx_messageInfo_Nodes_Node.Size(m)
}
func (m *Nodes_Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Nodes_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Nodes_Node proto.InternalMessageInfo

func (m *Nodes_Node) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Nodes_Node) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Nodes_Node) GetSize_() int64 {
	if m != nil {
		return m.Size_
	}
	return 0
}

func (m *Nodes_Node) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type Operation struct {
	Code                 Operation_Code `protobuf:"varint,1,opt,name=code,proto3,enum=rpc.Operation_Code" json:"code,omitempty"`
	Params               []string       `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty"`
	Ctx                  *Ctx           `protobuf:"bytes,3,opt,name=ctx,proto3" json:"ctx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Operation) Reset()         { *m = Operation{} }
func (m *Operation) String() string { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()    {}
func (*Operation) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fcbe24d8939e1f, []int{5}
}
func (m *Operation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operation.Unmarshal(m, b)
}
func (m *Operation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operation.Marshal(b, m, deterministic)
}
func (m *Operation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operation.Merge(m, src)
}
func (m *Operation) XXX_Size() int {
	return xxx_messageInfo_Operation.Size(m)
}
func (m *Operation) XXX_DiscardUnknown() {
	xxx_messageInfo_Operation.DiscardUnknown(m)
}

var xxx_messageInfo_Operation proto.InternalMessageInfo

func (m *Operation) GetCode() Operation_Code {
	if m != nil {
		return m.Code
	}
	return Operation_CP
}

func (m *Operation) GetParams() []string {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *Operation) GetCtx() *Ctx {
	if m != nil {
		return m.Ctx
	}
	return nil
}

func init() {
	proto.RegisterEnum("rpc.Operation_Code", Operation_Code_name, Operation_Code_value)
	proto.RegisterType((*Ctx)(nil), "rpc.Ctx")
	proto.RegisterType((*Empty)(nil), "rpc.Empty")
	proto.RegisterType((*DirPath)(nil), "rpc.DirPath")
	proto.RegisterType((*Path)(nil), "rpc.Path")
	proto.RegisterType((*Nodes)(nil), "rpc.Nodes")
	proto.RegisterType((*Nodes_Node)(nil), "rpc.Nodes.Node")
	proto.RegisterType((*Operation)(nil), "rpc.Operation")
}

func init() { proto.RegisterFile("consensus/rpc/fs.proto", fileDescriptor_14fcbe24d8939e1f) }

var fileDescriptor_14fcbe24d8939e1f = []byte{
	// 386 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4d, 0x8b, 0xd4, 0x40,
	0x10, 0x9d, 0xfe, 0x98, 0x59, 0x53, 0x2b, 0x1a, 0x5a, 0x58, 0xc2, 0x80, 0x30, 0xc4, 0x83, 0x01,
	0x21, 0x8b, 0x11, 0xfc, 0x01, 0x66, 0x14, 0x64, 0x8d, 0xbb, 0xf4, 0x61, 0x0f, 0xde, 0x62, 0xd2,
	0x92, 0xa0, 0x49, 0x9a, 0xee, 0x56, 0xb2, 0x9e, 0xbd, 0xfa, 0x0b, 0xfc, 0xb3, 0x52, 0x35, 0x1b,
	0x2f, 0xee, 0xce, 0x25, 0xfd, 0xea, 0xd5, 0x7b, 0x95, 0xd7, 0xa9, 0xc0, 0x59, 0x33, 0x8d, 0xde,
	0x8c, 0xfe, 0xbb, 0x3f, 0x77, 0xb6, 0x39, 0xff, 0xe2, 0x73, 0xeb, 0xa6, 0x30, 0x29, 0xe1, 0x6c,
	0x93, 0xbe, 0x00, 0x51, 0x86, 0x59, 0xc5, 0x20, 0xac, 0x33, 0x09, 0xdb, 0xb1, 0x2c, 0xd2, 0x08,
	0x95, 0x02, 0x39, 0x9a, 0x39, 0x24, 0x9c, 0x28, 0xc2, 0xe9, 0x09, 0xac, 0xdf, 0x0e, 0x36, 0xdc,
	0xa4, 0x17, 0x70, 0xb2, 0xef, 0xdd, 0x55, 0x1d, 0x3a, 0x74, 0xb6, 0xbd, 0x5b, 0x9c, 0x6d, 0xef,
	0xd0, 0x69, 0xeb, 0xd0, 0x2d, 0x4e, 0xc4, 0x6a, 0x0b, 0xa2, 0x09, 0x73, 0x22, 0x76, 0x2c, 0x3b,
	0x2d, 0x1e, 0xe4, 0xce, 0x36, 0x79, 0x19, 0x66, 0x8d, 0x64, 0xfa, 0x1a, 0x24, 0x4d, 0x5a, 0x7c,
	0xec, 0x7f, 0x1f, 0xbf, 0xcb, 0xf7, 0x8b, 0xc1, 0xfa, 0xe3, 0xd4, 0x1a, 0xaf, 0x9e, 0x81, 0x1c,
	0xa7, 0x16, 0xe3, 0x8b, 0xec, 0xb4, 0x78, 0x4c, 0x32, 0xea, 0xd0, 0x53, 0x53, 0x73, 0x7b, 0x0d,
	0x12, 0x2b, 0xba, 0x58, 0x3d, 0x2c, 0x77, 0x25, 0x8c, 0x5c, 0xb8, 0xb1, 0x86, 0xde, 0x23, 0x34,
	0x61, 0xe4, 0x7c, 0xff, 0xd3, 0x50, 0x66, 0xa1, 0x09, 0x23, 0xd7, 0xd5, 0xbe, 0x4b, 0xe4, 0xc1,
	0x8b, 0x38, 0xfd, 0xc3, 0x20, 0xba, 0xb4, 0xc6, 0xd5, 0xa1, 0x9f, 0x46, 0xf5, 0x1c, 0x64, 0x73,
	0x88, 0xc2, 0xb2, 0x47, 0xc5, 0x13, 0x8a, 0xf2, 0xaf, 0x9b, 0x97, 0x14, 0x07, 0x05, 0xea, 0x0c,
	0x36, 0xb6, 0x76, 0xf5, 0xe0, 0x13, 0xbe, 0x13, 0x59, 0xa4, 0x6f, 0xab, 0xa3, 0x5f, 0xea, 0x25,
	0x48, 0x9c, 0xa0, 0x36, 0xc0, 0xcb, 0xab, 0x78, 0x85, 0x67, 0x75, 0x1d, 0x33, 0x3c, 0x75, 0x15,
	0x73, 0x15, 0xc1, 0xba, 0xba, 0xd8, 0xbf, 0xd7, 0xb1, 0x40, 0xea, 0x83, 0x8f, 0x65, 0xf1, 0x9b,
	0xc1, 0xe6, 0x5d, 0xff, 0xcd, 0x5c, 0x5a, 0xb5, 0x03, 0x5e, 0x5a, 0xf5, 0x90, 0x46, 0xde, 0x6e,
	0x6f, 0x0b, 0x54, 0x1d, 0x96, 0xba, 0x42, 0x45, 0xf5, 0xe3, 0xa8, 0xe2, 0x29, 0x70, 0x3d, 0xa8,
	0x88, 0xb8, 0x3b, 0x07, 0xac, 0xab, 0xaf, 0xfb, 0xde, 0xdd, 0xab, 0x78, 0xc3, 0x3f, 0xad, 0x3e,
	0x6f, 0xe8, 0xff, 0x7b, 0xf5, 0x37, 0x00, 0x00, 0xff, 0xff, 0x9c, 0x87, 0xcc, 0x80, 0x99, 0x02,
	0x00, 0x00,
}
